def indonesiaToEnglish(kata):
    kamus = {
"kucing" : "cat",
"anjing" : "dog",
"gajah" : "elephant",
"kuda" : "horse",
"monyet" : "monkey",
"harimau" : "tiger",
"kupu-kupu" : "butterfly",
"ular" : "snake",
"burung" : "bird",
"ikan" : "fish",
"sapi" : "cow",
"kambing" : "goat",
"kelinci" : "rabbit",
"ayam" : "chicken",
"bebek" : "duck",
"kanguru" : "kangaroo",
"beruang" : "bear",
"serigala" : "wolf",
"singa" : "lion",
"kumbang" : "beetle",
"kupu-kupu malam" : "moth",
"kuda nil" : "hippopotamus",
"jerapah" : "giraffe",
"katak" : "frog",
"laba-laba" : "spider",
"lumba-lumba" : "dolphin",
"paus" : "whale",
"kelelawar" : "bat",
"tikus" : "mouse",
"kelomang" : "snail",
"cicak" : "lizard",
"koala" : "koala",
"capung" : "dragonfly",
"beo" : "parrot",
"merpati" : "pigeon",
"ruak-ruak" : "crocodile",
"kepiting" : "crab",
"babi" : "pig",
"ular python" : "python",
"kuda laut" : "seahorse",
"monyet ekor panjang" : "lemur",
"unta" : "camel",
"macan tutul" : "leopard",
"trenggiling" : "pangolin",
"landak" : "porcupine",
"gagak" : "crow",
"burung hantu" : "owl",
"kodok" : "toad",
"banteng" : "banteng",
"kura-kura" : "turtle",
"kakatua" : "cockatoo",
"penyu" : "turtle",
"simpanse" : "chimpanzee",
"komodo" : "komodo dragon",
"laba-laba hitam" : "black widow spider",
"hiu" : "shark",
"udang" : "shrimp",
"panda" : "panda",
"burung camar" : "seagull",
"ular cobra" : "cobra",
"gembala jantan" : "ram",
"burung gereja" : "sparrow",
"semut" : "ant",
"harimau bintang" : "star-nosed mole",
"lobster" : "lobster",
"penyu laut" : "sea turtle",
"macan" : "cheetah",
"kupu-kupu monark" : "monarch butterfly",
"elang" : "eagle",
"puma" : "puma",
"hiu paus" : "whale shark",
"bebek hutan" : "wood duck",
"kijang" : "deer",
"katak beracun" : "poison dart frog",
"laba-laba merah jambu" : "pink-toed tarantula",
"ayam jantan" : "rooster",
"kuda laut laut" : "sea horse",
"badak" : "rhinoceros",
"kelinci liar" : "wild rabbit",
"angsa" : "goose",
"cendrawasih" : "paradise bird",
"kupu-kupu raja" : "king butterfly",
"serigala kutub" : "arctic wolf",
"jerapah okapi" : "okapi",
"burung pemakan lebah" : "bee-eater bird",
"celeng" : "wild boar",
"ikan koi" : "koi fish",
"capung biru" : "blue dragonfly",
"ikan paus" : "swordfish",
"camar" : "lobster",
"laba-laba merah" : "red spider",
"kuda laut gergaji" : "sawfish",
"kancil" : "mouse deer",
"burung hantu elang" : "eagle owl",
"beruang kutub" : "polar bear",
"lalat" : "fly",
"bintang laut" : "starfish",
"babi hutan" : "wild pig",
"serigala hutan" : "woodland wolf",
"kuda laut putih" : "white seahorse",
"koala berjemur" : "sunbathing koala",
"burung beo" : "parakeet",
"bebek air" : "waterfowl",
"kalajengking" : "scorpion",
"rusa" : "stag",
"tikus air" : "water rat",
"kepiting pasir" : "sand crab",
"kuda laut hitam" : "black seahorse",
"kura-kura darat" : "box turtle",
"buaya air tawar" : "freshwater crocodile",
"merpati salju" : "snow dove",
"capung merah" : "red dragonfly",
"ikan hiu" : "hammerhead shark",
"domba" : "sheep",
"berang-berang" : "otter",
"burung kenari" : "canary",
"dinosaurus" : "dinosaur",
"kelinci cokelat" : "brown rabbit",
"serigala hitam" : "black wolf",
"burung camar laut" : "seagull",
"kepala angsa" : "swan",
"anjing laut" : "seal",
"kucing belang" : "tabby cat",
"kadal" : "lizard",
"gajah Afrika" : "African elephant",
"laba-laba emas" : "golden spider",
"paus putih" : "beluga whale",
"monyet langur" : "langur monkey",
"kanguru merah" : "red kangaroo",
"burung kasuari" : "cassowary",
"kelinci abu-abu" : "grey rabbit",
"capung kuning" : "yellow dragonfly",
"kucing siam" : "Siamese cat",
"kerbau" : "buffalo",
"katak hijau" : "green frog",
"ular cokelat" : "brown snake",
"kumbang hijau" : "green beetle",
"kecoa" : "cockroach",
"zebra" : "zebra",
"ular piton" : "python snake",
"lebah" : "bee",
"kupu-kupu oranye" : "orange butterfly",
"babi hutan hitam" : "black wild boar",
"laba-laba biru" : "blue spider",
"ikan gurame" : "gourami fish",
"serigala kelabu" : "grey wolf",
"laba-laba jaring emas" : "golden orb spider",
"angsa putih" : "white goose",
"burung hantu salju" : "snowy owl",
"kucing persia" : "Persian cat",
"laba-laba besar" : "tarantula",
"tikus putih" : "white mouse",
"ikan mas" : "goldfish",
"kelinci putih" : "white rabbit",
"ikan lele" : "catfish",
"beruang cokelat" : "brown bear",
"burung hantu besar" : "great horned owl",
"laba-laba hitam besar" : "giant black spider",
"kepiting air tawar" : "freshwater crab",
"elang laut" : "osprey",
"burung camar merah" : "red seagull",
"kupu-kupu kuning" : "yellow butterfly",
"babi hutan cokelat" : "brown wild pig",
"ikan pari" : "stingray",
"kuda zebra" : "zebra horse",
"burung hantu kecil" : "little owl",
"kupu-kupu ungu" : "purple butterfly",
"babi hutan putih" : "white wild boar",
"laba-laba merah besar" : "giant red spider",
"burung camar hijau" : "green seagull",
"kepiting air laut" : "sea crab",
"ikan tuna" : "tuna fish",
"laba-laba hijau" : "green spider",
"kucing hitam" : "black cat",
"ikan mas koki" : "koi carp",
"kelinci cokelat tua" : "dark brown rabbit",
"gajah India" : "Indian elephant",
"serigala hitam besar" : "giant black wolf",
"burung hantu cokelat" : "brown owl",
"laba-laba jaring emas besar" : "giant golden orb spider",
"angsa hitam" : "black swan",
"ular hijau" : "green snake",
"laba-laba merah jambu besar" : "giant pink-toed tarantula",
"ikan hiu besar" : "giant hammerhead shark",
"burung camar merah besar" : "giant red seagull",
"kupu-kupu biru besar" : "giant blue butterfly",
"babi hutan cokelat besar" : "giant brown wild pig",
"ikan lele besar" : "giant catfish",
"beruang cokelat besar" : "giant brown bear",
"burung camar hijau besar" : "giant green seagull",
"kuda zebra besar" : "giant zebra horse",
"kucing hitam besar" : "giant black cat",
"ikan mas koki besar" : "giant koi carp",
"gajah India besar" : "giant Indian elephant",
"kelinci cokelat tua besar" : "giant dark brown rabbit",
"serigala hitam besar" : "giant black wolf",
"laba-laba jaring emas besar" : "giant giant golden orb spider",
"angsa hitam besar" : "giant black swan",
"ular hijau besar" : "giant green snake"
    
    }
    return kamus.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA INGGRIS.")

def indonesiaToJapan(kata):
    kamus = {
"kucing": "neko",
"anjing": "inu",
"sapi": "ushi",
"burung": "tori",
"kelinci": "usagi",
"babi": "buta",
"ikan": "sakana",
"kura-kura": "kame",
"ular": "hebi",
"gajah": "zou",
"harimau": "tora",
"kuda": "uma",
"kirin": "kirin",
"kepiting": "sarugani",
"rubah": "kitsune",
"anjing Akita": "akita inu",
"tengu": "tengu",
"tanuki": "tanuki",
"monyet": "saru",
"burung gereja": "suzume",
"kuda laut": "ushiwaka",
"paus": "kujira",
"ikan koi": "koi",
"lebah": "hachi",
"keong api": "hotaru",
"gurita": "ika",
"merak": "kujaku",
"berang-berang": "kawauso",
"beruang": "kuma",
"kelelawar": "komori",
"kupu-kupu": "konoha",
"kambing liar": "kamoshika",
"kanaria": "kanaria",
"koala": "koala",
"kelinci laut": "korin",
"rusa": "shika",
"burung camar": "shachou",
"singa": "shishi",
"hiu": "shark",
"jaguar": "jaguar",
"kupu-kupu": "joou",
"gurita": "tako",
"tengu": "tengu",
"tanuki": "tanuki",
"burung": "tori",
"kadal": "tokage",
"capung": "tombo",
"buaya": "nigai",
"boneka": "nuigurumi",
"hamster": "hamu",
"ayam muda": "hiyoko",
"gajah laut": "bou",
"burung phoenix": "houou",
"burung hantu": "fukurou",
"penguin": "pen",
"panda": "panda",
"kepiting": "pipi",
"kelabang": "hirameki",
"tapir": "baku",
"bajak laut": "mujaki",
"serangga": "mushi",
"kambing": "yagi",
"gecko": "yamori",
"kuda nil": "rakuda",
"singa": "raion",
"rubah": "regu",
"rusa kutub": "reindeer",
"gembala": "roba",
"hantu Jepang": "rokurokubi",
"buaya": "wani",
"elang": "washi",
"sapi": "ushi",
"burung robin": "ukitsumomiji",
"belut": "unagi",
"ulat daun": "enokimushi",
"udang": "ebi"
    
    }
    
    return kamus.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA JEPANG.")