def englishToIndonesia(kata):
    kamus = {
"cat": "kucing",
"dog": "anjing",
"elephant": "gajah",
"horse": "kuda",
"monkey": "monyet",
"tiger": "harimau",
"butterfly": "kupu-kupu",
"snake": "ular",
"bird": "burung",
"fish": "ikan",
"cow": "sapi",
"goat": "kambing",
"rabbit": "kelinci",
"chicken": "ayam",
"duck": "bebek",
"kangaroo": "kanguru",
"bear": "beruang",
"wolf": "serigala",
"lion": "singa",
"beetle": "kumbang",
"moth": "kupu-kupu malam",
"hippopotamus": "kuda nil",
"giraffe": "jerapah",
"frog": "katak",
"spider": "laba-laba",
"dolphin": "lumba-lumba",
"whale": "paus",
"bat": "kelelawar",
"mouse": "tikus",
"snail": "kelomang",
"lizard": "cicak",
"koala": "koala",
"dragonfly": "capung",
"parrot": "beo",
"pigeon": "merpati",
"crocodile": "ruak-ruak",
"crab": "kepiting",
"pig": "babi",
"python": "ular python",
"seahorse": "kuda laut",
"lemur": "monyet ekor panjang",
"camel": "unta",
"leopard": "macan tutul",
"pangolin": "trenggiling",
"porcupine": "landak",
"crow": "gagak",
"owl": "burung hantu",
"toad": "kodok",
"banteng": "banteng",
"turtle": "kura-kura",
"cockatoo": "kakatua",
"turtle": "penyu",
"chimpanzee": "simpanse",
"komodo dragon": "komodo",
"black widow spider": "laba-laba hitam",
"shark": "hiu",
"shrimp": "udang",
"panda": "panda",
"seagull": "burung camar",
"cobra": "ular cobra",
"ram": "gembala jantan",
"sparrow": "burung gereja",
"ant": "semut",
"star-nosed mole": "harimau bintang",
"lobster": "lobster",
"sea turtle": "penyu laut",
"cheetah": "macan",
"monarch butterfly": "kupu-kupu monark",
"eagle": "elang",
"puma": "puma",
"whale shark": "hiu paus",
"wood duck": "bebek hutan",
"deer": "kijang",
"poison dart frog": "katak beracun",
"pink-toed tarantula": "laba-laba merah jambu",
"rooster": "ayam jantan",
"sea horse": "kuda laut laut",
"rhinoceros": "badak",
"wild rabbit": "kelinci liar",
"goose": "angsa",
"paradise bird": "cendrawasih",
"king butterfly": "kupu-kupu raja",
"arctic wolf": "serigala kutub",
"okapi": "jerapah okapi",
"bee-eater bird": "burung pemakan lebah",
"wild boar": "celeng",
"koi fish": "ikan koi",
"blue dragonfly": "capung biru",
"swordfish": "ikan paus",
"lobster": "camar",
"red spider": "laba-laba merah",
"sawfish": "kuda laut gergaji",
"mouse deer": "kancil",
"eagle owl": "burung hantu elang",
"polar bear": "beruang kutub",
"fly": "lalat",
"starfish": "bintang laut",
"wild pig": "babi hutan",
"woodland wolf": "serigala hutan",
"white seahorse": "kuda laut putih",
"sunbathing koala": "koala berjemur",
"parakeet": "burung beo",
"waterfowl": "bebek air",
"scorpion": "kalajengking",
"stag": "rusa",
"water rat": "tikus air",
"sand crab": "kepiting pasir",
"black seahorse": "kuda laut hitam",
"box turtle": "kura-kura darat",
"freshwater crocodile": "buaya air tawar",
"snow dove": "merpati salju",
"red dragonfly": "capung merah",
"hammerhead shark": "ikan hiu",
"sheep": "domba",
"otter": "berang-berang",
"canary": "burung kenari",
"dinosaur": "dinosaurus",
"brown rabbit": "kelinci cokelat",
"black wolf": "serigala hitam",
"seagull": "burung camar laut",
"swan": "kepala angsa",
"seal": "anjing laut",
"tabby cat": "kucing belang",
"lizard": "kadal",
"African elephant": "gajah Afrika",
"golden spider": "laba-laba emas",
"beluga whale": "paus putih",
"langur monkey": "monyet langur",
"red kangaroo": "kanguru merah",
"cassowary": "burung kasuari",
"grey rabbit": "kelinci abu-abu",
"yellow dragonfly": "capung kuning",
"Siamese cat": "kucing siam",
"buffalo": "kerbau",
"green frog": "katak hijau",
"brown snake": "ular cokelat",
"green beetle": "kumbang hijau",
"cockroach": "kecoa",
"zebra": "zebra",
"python snake": "ular piton",
"bee": "lebah",
"orange butterfly": "kupu-kupu oranye",
"black wild boar": "babi hutan hitam",
"blue spider": "laba-laba biru",
"gourami fish": "ikan gurame",
"grey wolf": "serigala kelabu",
"golden orb spider": "laba-laba jaring emas",
"white goose": "angsa putih",
"snowy owl": "burung hantu salju",
"Persian cat": "kucing persia",
"tarantula": "laba-laba besar",
"white mouse": "tikus putih",
"goldfish": "ikan mas",
"white rabbit": "kelinci putih",
"catfish": "ikan lele",
"brown bear": "beruang cokelat",
"great horned owl": "burung hantu besar",
"giant black spider": "laba-laba hitam besar",
"freshwater crab": "kepiting air tawar",
"osprey": "elang laut",
"red seagull": "burung camar merah",
"yellow butterfly": "kupu-kupu kuning",
"brown wild pig": "babi hutan cokelat",
"stingray": "ikan pari",
"zebra horse": "kuda zebra",
"little owl": "burung hantu kecil",
"purple butterfly": "kupu-kupu ungu",
"white wild boar": "babi hutan putih",
"giant red spider": "laba-laba merah besar",
"giant green seagull": "burung camar hijau besar",
"sea crab": "kepiting air laut",
"tuna fish": "ikan tuna",
"green spider": "laba-laba hijau",
"black cat": "kucing hitam",
"koi carp": "ikan mas koki",
"dark brown rabbit": "kelinci cokelat tua",
"Indian elephant": "gajah India",
"giant black wolf": "serigala hitam besar",
"brown owl": "burung hantu cokelat",
"giant golden orb spider": "laba-laba jaring emas besar",
"black swan": "angsa hitam",
"giant green snake": "ular hijau besar"
    }
    
    return kamus.get(kata, "KATA TIDAK DITEMUKAN DALAM KAMUS INDONESIA")


def englishToJapan(kata):
    kamus = {
"cat" : "neko",
"dog": "inu",
"elephant": "zou",
"horse": "uma",
"monkey": "saru",
"tiger": "tora",
"butterfly": "cho",
"snake": "hebi",
"bird": "tori",
"fish": "sakana",
"cow": "ushi",
"goat": "yagi",
"rabbit": "usagi",
"chicken": "niwatori",
"duck": "ahiru",
"kangaroo": "kangaru",
"bear": "kuma",
"wolf": "okami",
"lion": "raion",
"beetle": "mushi",
"moth": "ga",
"hippopotamus": "kaba",
"giraffe": "kirin",
"frog": "kaeru",
"spider": "kumo",
"dolphin": "iruka",
"whale": "kujira",
"bat": "koumori",
"mouse": "nezumi",
"snail": "katatsumuri",
"lizard": "tokage",
"koala": "koala",
"dragonfly": "tonbo",
"parrot": "inko",
"pigeon": "hato",
"crocodile": "wani",
"crab": "kani",
"pig": "buta",
"python": "paiton",
"seahorse": "umihoshi",
"lemur": "remuru",
"camel": "rakuda",
"leopard": "hyou",
"pangolin": "yamori",
"porcupine": "yamakuzuri",
"crow": "karasu",
"owl": "fukurou",
"toad": "hiki",
"banteng": "banteng",
"turtle": "kame",
"cockatoo": "kakatou",
"turtle": "kame",
"chimpanzee": "chimpanji",
"komodo dragon": "komodo doragon",
"black widow spider": "burakku widou kumo",
"shark": "same",
"shrimp": "ebi",
"panda": "panda",
"seagull": "kamome",
"cobra": "koubura",
"ram": "ramu",
"sparrow": "suzume",
"ant": "ari",
"star-nosed mole": "sutaanouzu mooru",
"lobster": "robusutaa",
"sea turtle": "umigame",
"cheetah": "chiita",
"monarch butterfly": "mOnaaku chou",
"eagle": "washi",
"puma": "puma",
"whale shark": "huriru shaku",
"wood duck": "mokusei",
"deer": "shika",
"poison dart frog": "dokuhirokaeru",
"pink-toed tarantula": "pinku toodo taranchura",
"rooster": "niwatori",
"sea horse": "umihoshi",
"rhinoceros": "saihinocerosu",
"wild rabbit": "yaseiusagi",
"goose": "gacha",
"paradise bird": "paradaisu baado",
"king butterfly": "kingu chou",
"arctic wolf": "akuteikku urufu",
"okapi": "okapi",
"bee-eater bird": "bii itaa",
"wild boar": "yasei buta",
"koi fish": "koi",
"blue dragonfly": "buruu tonbo",
"swordfish": "ken hirameki",
"lobster": "robusutaa",
"red spider": "reddo supaida",
"white seahorse": "howaito umihoshi",
"sunbathing koala": "hiyake no koara",
"parakeet": "o-mume-sama",
"waterfowl": "suichu rui",
"scorpion": "sasori",
"stag": "kanuka",
"water rat": "mizu nezumi",
"sand crab": "suna gani",
"black seahorse": "burakku umihoshi",
"box turtle": "hako kame",
"freshwater crocodile": "seisui wani",
"snow dove": "yuki hato",
"red dragonfly": "akai tonbo",
"hammerhead shark": "hanmaa heddo shaku",
"sheep": "hitsuji",
"otter": "kawauso",
"canary": "kanaria",
"dinosaur": "kyoryu",
"brown rabbit": "chairoi usagi",
"black wolf": "kuroi ookami",
"seagull": "kamome",
"swan": "hakucho",
"seal": "azarashi",
"tabby cat": "tora neko",
"lizard": "tokage",
"African elephant": "afurika zou",
"golden spider": "kogane no kumo",
"beluga whale": "beruga kujira",
"langur monkey": "ranguru saru",
"red kangaroo": "akai kangaru",
"cassowary": "kassowari",
"grey rabbit": "haiiro no usagi",
"yellow dragonfly": "kiro tonbo",
"brown snake": "chairoi hebi",
"green beetle": "midori mushi",
"cockroach": "gokiburi",
"zebra": "zebra",
"python snake": "paiton hebi",
"bee": "hachi",
"orange butterfly": "orenji no chou",
"black wild boar": "kuroi yasei buta",
"blue spider": "aoi kumo",
"gourami fish": "gurame",
"grey wolf": "haiiro no ookami",
"golden orb spider": "konjiki no kumo",
"white goose": "shiroi gacha",
"snowy owl": "yuki fukurou",
"Persian cat": "perushan neko",
"tarantula": "taranchura",
"white mouse": "shiroi nezumi",
"goldfish": "kingyo",
"white rabbit": "shiroi usagi",
"catfish": "namazu",
"brown bear": "chairoi kuma",
"great horned owl": "gureito honnodo",
"giant black spider": "kyodai kuroi kumo",
"freshwater crab": "seisui kani",
"osprey": "osupurei",
"red seagull": "akai kamome",
"yellow butterfly": "kiiro no chou",
"brown wild pig": "chairoi yasei buta",
"stingray": "sutinrei",
"zebra horse": "zebura uma",
"little owl": "ritoru fukurou",
"purple butterfly": "murasaki no chou",
"white wild boar": "shiroi yasei buta",
"giant red spider": "kyodai akai kumo",
"green seagull": "midori kamome",
"sea crab": "umi gani",
"tuna fish": "maguro",
"green spider": "midori no kumo",
"black cat": "kuroi neko",
"koi carp": "koi koi",
"dark brown rabbit": "kurokuroi usagi",
"Indian elephant": "indo zou",
"giant black wolf": "kyodai kuroi ookami",
"brown owl": "chairoi fukurou",
"giant golden orb spider": "kyodai konjiki no kumo",
"black swan": "kuroi hakucho",
"green snake": "midori hebi",
"giant pink-toed tarantula": "kyodai pinku toodo taranchura",
"giant hammerhead shark": "kyodai hanmaa heddo shaku",
"giant red seagull": "kyodai akai kamome",
"giant blue butterfly": "kyodai aoi chou",
"giant brown wild pig": "kyodai chairoi yasei buta",
"giant catfish": "kyodai namazu",
"giant brown bear": "kyodai chairoi kuma",
"giant green seagull": "kyodai midori kamome",
"giant zebra horse": "kyodai zebura uma",
"giant black cat": "kyodai kuroi neko",
"giant koi carp": "kyodai koi koi",
"giant Indian elephant": "kyodai indo zou",
"giant dark brown rabbit": "kyodai kurokuroi usagi",
"giant black wolf": "kyodai kuroi ookami",
"giant giant golden orb spider": "kyodai kyodai konjiki no kumo",
"giant black swan": "kyodai kuroi hakucho",
"giant green snake": "kyodai midori hebi"
    }
    
    return kamus.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA JEPANG.")