def japanToIndonesia(kata):
    kamus = {
"neko": "kucing",
"inu": "anjing",
"ushi": "sapi",
"tori": "burung",
"usagi": "kelinci",
"buta": "babi",
"sakana": "ikan",
"kame": "kura-kura",
"hebi": "ular",
"zou": "gajah",
"tora": "harimau",
"uma": "kuda",
"kirin": "kirin",
"sarugani": "kepiting",
"kitsune": "rubah",
"akita inu": "anjing Akita",
"tengu": "tengu",
"tanuki": "tanuki",
"saru": "monyet",
"suzume": "burung gereja",
"ushiwaka": "kuda laut",
"kujira": "paus",
"koi": "ikan koi",
"hachi": "lebah",
"hotaru": "keong api",
"ika": "gurita",
"kujaku": "merak",
"kawauso": "berang-berang",
"kuma": "beruang",
"komori": "kelelawar",
"konoha": "kupu-kupu",
"kamoshika": "kambing liar",
"kanaria": "kanaria",
"koala": "koala",
"korin": "kelinci laut",
"shika": "rusa",
"shachou": "burung camar",
"shishi": "singa",
"shark": "hiu",
"jaguar": "jaguar",
"joou": "kupu-kupu",
"tako": "gurita",
"tengu": "tengu",
"tanuki": "tanuki",
"tori": "burung",
"tokage": "kadal",
"tombo": "capung",
"nigai": "buaya",
"nuigurumi": "boneka",
"hamu": "hamster",
"hiyoko": "ayam muda",
"bou": "gajah laut",
"houou": "burung phoenix",
"fukurou": "burung hantu",
"pen": "penguin",
"panda": "panda",
"pipi": "kepiting",
"hirameki": "kelabang",
"baku": "tapir",
"mujaki": "bajak laut",
"mushi": "serangga",
"yagi": "kambing",
"yamori": "gecko",
"rakuda": "kuda nil",
"raion": "singa",
"regu": "rubah",
"reindeer": "rusa kutub",
"roba": "gembala",
"rokurokubi": "hantu Jepang",
"wani": "buaya",
"washi": "elang",
"ushi": "sapi",
"ukitsumomiji": "burung robin",
"unagi": "belut",
"enokimushi": "ulat daun",
"ebi": "udang",

    }

    return kamus.get(kata, "KATA TIDAK DITEMUKAN DALAM KAMUS INDONESIA")

def japanToEnglish(kata):
    kamus = {
"neko": "cat",
"inu": "dog",
"zou": "elephant",
"uma": "horse",
"saru": "monkey",
"tora": "tiger",
"cho": "butterfly",
"hebi": "snake",
"tori": "bird",
"sakana": "fish",
"ushi": "cow",
"yagi": "goat",
"usagi": "rabbit",
"niwatori": "chicken",
"ahiru": "duck",
"kangaru": "kangaroo",
"kuma": "bear",
"okami": "wolf",
"raion": "lion",
"mushi": "beetle",
"ga": "moth",
"kaba": "hippopotamus",
"kirin": "giraffe",
"kaeru": "frog",
"kumo": "spider",
"iruka": "dolphin",
"kujira": "whale",
"koumori": "bat",
"nezumi": "mouse",
"katatsumuri": "snail",
"tokage": "lizard",
"koala": "koala",
"tonbo": "dragonfly",
"inko": "parrot",
"hato": "pigeon",
"wani": "crocodile",
"kani": "crab",
"buta": "pig",
"paiton": "python",
"umihoshi": "seahorse",
"remuru": "lemur",
"rakuda": "camel",
"hyou": "leopard",
"yamori": "pangolin",
"yamakuzuri": "porcupine",
"karasu": "crow",
"fukurou": "owl",
"hiki": "toad",
"banteng": "banteng",
"kame": "turtle",
"kakatou": "cockatoo",
"kame": "turtle",
"chimpanji": "chimpanzee",
"komodo doragon": "komodo dragon",
"burakku widou kumo": "black widow spider",
"same": "shark",
"ebi": "shrimp",
"panda": "panda",
"kamome": "seagull",
"koubura": "cobra",
"ramu": "ram",
"suzume": "sparrow",
"ari": "ant",
"sutaanouzu mooru": "star-nosed mole",
"robusutaa": "lobster",
"umigame": "sea turtle",
"chiita": "cheetah",
"mOnaaku chou": "monarch butterfly",
"washi": "eagle",
"puma": "puma",
"huriru shaku": "whale shark",
"mokusei": "wood duck",
"shika": "deer",
"dokuhirokaeru": "poison dart frog",
"pinku toodo taranchura": "pink-toed tarantula",
"niwatori": "rooster",
"umihoshi": "seahorse",
"saihinocerosu": "rhinoceros",
"yaseiusagi": "wild rabbit",
"gacha": "goose",
"paradaisu baado": "paradise bird",
"kingu chou": "king butterfly",
"akuteikku urufu": "arctic wolf",
"okapi": "okapi",
"bii itaa": "bee-eater bird",
"yasei buta": "wild boar",
"koi": "koi fish",
"buruu tonbo": "blue dragonfly",
"ken hirameki": "swordfish",
"robusutaa": "lobster",
"reddo supaida": "red spider",
"howaito umihoshi": "white seahorse",
"hiyake no koara": "sunbathing koala",
"o-mume-sama": "parakeet",
"suichu rui": "waterfowl",
"sasori": "scorpion",
"kanuka": "stag",
"mizu nezumi": "water rat",
"suna gani": "sand crab",
"burakku umihoshi": "black seahorse",
"hako kame": "box turtle",
"seisui wani": "freshwater crocodile",
"yuki hato": "snow dove",
"akai tonbo": "red dragonfly",
"hanmaa heddo shaku": "hammerhead shark",
"hitsuji": "sheep",
"kawauso": "otter",
"kanaria": "canary",
"kyoryu": "dinosaur",
"chairoi usagi": "brown rabbit",
"kuroi ookami": "black wolf",
"kamome": "seagull",
"hakucho": "swan",
"azarashi": "seal",
"tora neko": "tabby cat",
"tokage": "lizard",
"afurika zou": "African elephant",
"kogane no kumo": "golden spider",
"beruga kujira": "beluga whale",
"ranguru saru": "langur monkey",
"akai kangaru": "red kangaroo",
"kassowari": "cassowary",
"haiiroi usagi": "grey rabbit",
"kiro tonbo": "yellow dragonfly",
"chairoi hebi": "brown snake",
"midori mushi": "green beetle",
"gokiburi": "cockroach",
"zebra": "zebra",
"paiton hebi": "python snake",
"hachi": "bee",
"orenji no chou": "orange butterfly",
"kuroi yasei buta": "black wild boar",
"aoi kumo": "blue spider",
"gurame": "gourami fish",
"haiiro no ookami": "grey wolf",
"konjiki no kumo": "golden orb spider",
"shiroi gacha": "white goose",
"yuki fukurou": "snowy owl",
"perushan neko": "Persian cat",
"taranchura": "tarantula",
"shiroi nezumi": "white mouse",
"kingyo": "goldfish",
"shiroi usagi": "white rabbit",
"namazu": "catfish",
"chairoi kuma": "brown bear",
"gureito honnodo": "great horned owl",
"kyodai kuroi kumo": "giant black spider",
"seisui kani": "freshwater crab",
"osupurei": "osprey",
"akai kamome": "red seagull",
"kiiro no chou": "yellow butterfly",
"chairoi yasei buta": "brown wild pig",
"sutinrei": "stingray",
"zebura uma": "zebra horse",
"ritoru fukurou": "little owl",
"murasaki no chou": "purple butterfly",
"shiroi yasei buta": "white wild boar",
"kyodai akai kumo": "giant red spider",
"midori kamome": "giant green seagull",
"umi gani": "sea crab",
"maguro": "tuna fish",
"midori no kumo": "green spider",
"kuroi neko": "black cat",
"koi koi": "koi carp",
"kurokuroi usagi": "dark brown rabbit",
"indo zou": "Indian elephant",
"kyodai kuroi ookami": "giant black wolf",
"chairoi fukurou": "brown owl",
"kyodai konjiki no kumo": "giant golden orb spider",
"kuroi hakucho": "black swan",
"midori hebi": "green snake",
"kyodai pinku toodo taranchura": "giant pink-toed tarantula",
"kyodai hanmaa heddo shaku": "giant hammerhead shark",
"kyodai akai kamome": "giant red seagull",
"kyodai aoi chou": "giant blue butterfly",
"kyodai chairoi yasei buta": "giant brown wild pig",
"kyodai namazu": "giant catfish",
"kyodai chairoi kuma": "giant brown bear",
"kyodai midori kamome": "giant green seagull",
"kyodai zebura uma": "giant zebra horse",
"kyodai kuroi neko": "giant black cat",
"kyodai koi koi": "giant koi carp",
"kyodai indo zou": "giant Indian elephant",
"kyodai kurokuroi usagi": "giant dark brown rabbit",
"kyodai kuroi ookami": "giant black wolf",
"kyodai kyodai konjiki no kumo": "giant giant golden orb spider",
"kyodai kuroi hakucho": "giant black swan",
"kyodai midori hebi": "giant green snake",


    }

    return kamus.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA INGGRIS.")