def english(text):
    eng= [
            "cat",
            "dog",
            "elephant",
            "horse",
            "monkey",
            "tiger",
            "butterfly",
            "snake",
            "bird",
            "fish",
            "cow",
            "goat",
            "rabbit",
            "chicken",
            "duck",
            "kangaroo",
            "bear",
            "wolf",
            "lion",
            "beetle",
            "moth",
            "hippopotamus",
            "giraffe",
            "frog",
            "spider",
            "dolphin",
            "whale",
            "bat",
            "mouse",
            "snail",
            "lizard",
            "koala",
            "dragonfly",
            "parrot",
            "pigeon",
            "crocodile",
            "crab",
            "pig",
            "python",
            "seahorse",
            "lemur",
            "camel",
            "leopard",
            "pangolin",
            "porcupine",
            "crow",
            "owl",
            "toad",
            "banteng",
            "turtle",
            "cockatoo",
            "turtle",
            "chimpanzee",
            "komodo dragon",
            "black widow spider",
            "shark",
            "shrimp",
            "panda",
            "seagull",
            "cobra",
            "ram",
            "sparrow",
            "ant",
            "star-nosed mole",
            "lobster",
            "sea turtle",
            "cheetah",
            "monarch butterfly",
            "eagle",
            "puma",
            "whale shark",
            "wood duck",
            "deer",
            "poison dart frog",
            "pink-toed tarantula",
            "rooster",
            "sea horse",
            "rhinoceros",
            "wild rabbit",
            "goose",
            "paradise bird",
            "king butterfly",
            "arctic wolf",
            "okapi",
            "bee-eater bird",
            "wild boar",
            "koi fish",
            "blue dragonfly",
            "swordfish",
            "lobster",
            "red spider",
            "white seahorse",
            "sunbathing koala",
            "parakeet",
            "waterfowl",
            "scorpion",
            "stag",
            "water rat",
            "sand crab",
            "black seahorse",
            "box turtle",
            "freshwater crocodile",
            "snow dove",
            "red dragonfly",
            "hammerhead shark",
            "sheep",
            "otter",
            "canary",
            "dinosaur",
            "brown rabbit",
            "black wolf",
            "seagull",
            "swan",
            "seal",
            "tabby cat",
            "lizard",
            "African elephant",
            "golden spider",
            "beluga whale",
            "langur monkey",
            "red kangaroo",
            "cassowary",
            "grey rabbit",
            "yellow dragonfly",
            "brown snake",
            "green beetle",
            "cockroach",
            "zebra",
            "python snake",
            "bee",
            "orange butterfly",
            "black wild boar",
            "blue spider",
            "gourami fish",
            "grey wolf",
            "golden orb spider",
            "white goose",
            "snowy owl",
            "Persian cat",
            "tarantula",
            "white mouse",
            "goldfish",
            "white rabbit",
            "catfish",
            "brown bear",
            "great horned owl",
            "giant black spider",
            "freshwater crab",
            "osprey",
            "red seagull",
            "yellow butterfly",
            "brown wild pig",
            "stingray",
            "zebra horse",
            "little owl",
            "purple butterfly",
            "white wild boar",
            "giant red spider",
            "green seagull",
            "sea crab",
            "tuna fish",
            "green spider",
            "black cat",
            "koi carp",
            "dark brown rabbit",
            "Indian elephant",
            "giant black wolf",
            "brown owl",
            "giant golden orb spider",
            "black swan",
            "green snake",
            "giant pink-toed tarantula",
            "giant hammerhead shark",
            "giant red seagull",
            "giant blue butterfly",
            "giant brown wild pig",
            "giant catfish",
            "giant brown bear",
            "giant green seagull",
            "giant zebra horse",
            "giant black cat",
            "giant koi carp",
            "giant Indian elephant",
            "giant dark brown rabbit",
            "giant black wolf",
            "giant black swan",
            "giant green snake"
    ]
    
    return eng